### ISSUE TITLE
Errors with angular-cli

### ISSUE THREAD

**Issue by NilsQuirmbach** [apoterenko/angular2-cache#1]
I wanted to use angular2-cache in combination with angular-cli, but some errors occur. I made a sample project.

https://github.com/NilsQuirmbach/angular2-cache-cli

**Comment by NilsQuirmbach** [comment]
Pretty easy fix, add ts-smart-logger as a dev-dependency and it works

**Comment by apoterenko** [comment]
The logger needs as a part of the module, therefore I have appended it as peerDep..
What kind of error occurred?

**Comment by NilsQuirmbach** [comment]
ERROR in ./~/angular2-cache/zone/NgZoneGlobalCache.js
Module not found: Error: Can't resolve 'ts-smart-logger/index' in 'D:\Development\cli-cache\node_modules\angular2-cache\zone'
 @ ./~/angular2-cache/zone/NgZoneGlobalCache.js 8:14-46
 @ ./~/angular2-cache/index.js
 @ ./src/app/app.component.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2-cache/Cache.js
Module not found: Error: Can't resolve 'ts-smart-logger/index' in 'D:\Development\cli-cache\node_modules\angular2-cache'
 @ ./~/angular2-cache/Cache.js 2:14-46
 @ ./~/angular2-cache/memory/MemoryCache.js
 @ ./~/angular2-cache/index.js
 @ ./src/app/app.component.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

**Comment by apoterenko** [comment]
You should append the logger into dependencies section

**Comment by NilsQuirmbach** [comment]
I know, did that already.
