### ISSUE TITLE
angular2-cache doesnt work with latest angular2 release

### ISSUE THREAD

**Issue by swatisinha09** [apoterenko/angular2-cache#4]
Steps Executed:-
1) Downloaded angular seed project from angular site.
2) Doing npm install angular2-cache for the project .
3)  Included the CacheModule in app.module.ts from angular2-cache/index .
4) Post this, on bringing up the application getting the below error:-
**Failed to load resource: the server responded with a status of 404 (Not Found) for http://localhost:44581/angular2-cache/index**

Can someone please address this

**Comment by apoterenko** [comment]
Updated to 4.0.0-rc.5
